### ISSUE TITLE
Can't find velodyne_pointcloud

### ISSUE THREAD

**Issue by MostafaOsman144** [epan-utbm/utbm_robocar_dataset#5]
In the launch file, the velodyne_pointcloud directory is used to launch the velodyne_left_nodelet_manager and the velodyne_right_nodelet_manager. I can't find it in the repo and when trying to launch the launch file, It returns the following error:

ResourceNotFound: velodyne_pointcloud.

**Comment by MostafaOsman144** [comment]
Ok, This directory is in the ROS velodyne driver. You need to clone the ROS velodyne driver to you catkin_ws before you try to run the launch files.

**Comment by hichem-abdellali** [comment]
Hi

Can I ask you please to explain what to copy to where ? 

Thanks
